---
abstract: 'Log::Minimal extension to support indentation'
author:
  - 'Daisuke (yet another) Maki <maki.daisuke AT gmail.com>'
build_requires:
  Test::More: 0.98
  Test::Output: 1.02
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.8.0, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Minimal-Indent
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  Log::Minimal::Indent:
    file: lib/Log/Minimal/Indent.pm
    version: 0.01
requires:
  Guard: 1.021
  Log::Minimal: 0
  perl: 5.010000
resources:
  bugtracker: https://github.com/Maki-Daisuke/p5-Log-Minimal-Indent/issues
  homepage: https://github.com/Maki-Daisuke/p5-Log-Minimal-Indent
  repository: https://github.com/Maki-Daisuke/p5-Log-Minimal-Indent.git
version: 0.01
x_contributors:
  - 'Daisuke (yet another) Maki <maki.daisuke@gmail.com>'
